# This workflow runs checks and publishes the package to npm when a release is created.

name: Node.js Package

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}
